; PlatformIO Project Configuration File – KnockKnock Gateway
;
; Target: ESP32-C3 DevKitM-1
; Framework: ESP-IDF (native)


[env:v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf
monitor_speed = 115200


[env:c3]
platform = espressif32@6.7.0
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
build_flags = -D C3_BUILD
board_build.partitions = partitions.csv

[env:s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

board_build.flash_size = 4MB
board_upload.flash_size = 4MB

; Allineiamo la modalità di lettura a quella rilevata dal bootloader
board_build.flash_mode = dio
board_build.partitions = partitions_singleapp.csv

; Per evitare che la console USB nativa si impalli al riavvio
monitor_rts = 0
monitor_dtr = 0