[agent]
  interval = "10s"
  flush_interval = "10s"

[[inputs.mqtt_consumer]]
  servers   = ["tcp://mosquitto:1883"]
  topics    = ["knockknock/#"]
  data_format = "json"
  json_time_key = "timestamp_ms"
  json_time_format = "unix_ms"
  tag_keys  = ["node_id", "event_type"]

[[outputs.influxdb_v2]]
  urls         = ["http://influxdb:8086"]
  token        = "knockknock-super-secret-token"
  organization = "knockknock"
  bucket       = "sensors"
