#include <string.h>
#include "cloud_task.h"
#include "config.h"
#include "hub.h"
#include "esp_log.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "nvs_flash.h"
#include "mqtt_client.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_sntp.h"

// ESP Provisioning & Custom Configuration Includes
#include <wifi_provisioning/manager.h>
#include <wifi_provisioning/scheme_ble.h>
#include "cJSON.h"
#include "secure_store.h"

static const char *TAG = "CLOUD";

// Dynamic configuration keys for NVS secure store
#define NVS_KEY_CA_CERT "cloud_ca_cert"
#define NVS_KEY_BROKER_URI "cloud_broker_uri"
#define NVS_KEY_USERNAME "cloud_username"
#define NVS_KEY_PASSWORD "cloud_password"

/* Embedded CA certificate — generated by mosquitto/gen_certs.sh.
 * IDF EMBED_TXTFILES places the PEM (null-terminated) at this symbol. */
extern const uint8_t _binary_certs_ca_crt_start[];

static EventGroupHandle_t s_wifi_event_group;
static const int CONNECTED_BIT = BIT0;
static esp_mqtt_client_handle_t s_mqtt_client = NULL;

static bool s_provisioning_mode = false;

// Static buffers to hold loaded credentials securely for the MQTT client
static char s_cloud_ca_cert[2048] = {0};
static char s_cloud_broker_uri[256] = {0};
static char s_cloud_username[64] = {0};
static char s_cloud_password[64] = {0};

static void event_handler(void* arg, esp_event_base_t event_base,
                                int32_t event_id, void* event_data) {
    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START) {
        if (!s_provisioning_mode) {
            esp_wifi_connect();
        }
    } else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED) {
        if (!s_provisioning_mode) {
            esp_wifi_connect();
        }
        xEventGroupClearBits(s_wifi_event_group, CONNECTED_BIT);
        ESP_LOGI(TAG, "Retry connecting to the AP");
    } else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
        xEventGroupSetBits(s_wifi_event_group, CONNECTED_BIT);
        ESP_LOGI(TAG, "Got IP");
    }
}

// Provisioning event handler for logging and state management
static void prov_event_handler(void* arg, esp_event_base_t event_base,
                               int32_t event_id, void* event_data) {
    if (event_base == WIFI_PROV_EVENT) {
        switch (event_id) {
            case WIFI_PROV_START:
                ESP_LOGI(TAG, "Provisioning service started successfully");
                break;
            case WIFI_PROV_CRED_RECV: {
                wifi_sta_config_t *wifi_config = (wifi_sta_config_t *)event_data;
                ESP_LOGI(TAG, "Received Wi-Fi credentials: SSID: %s", (char *)wifi_config->ssid);
                break;
            }
            case WIFI_PROV_CRED_FAIL: {
                wifi_prov_sta_fail_reason_t *reason = (wifi_prov_sta_fail_reason_t *)event_data;
                ESP_LOGE(TAG, "Provisioning failed to connect to Wi-Fi. Reason: %s",
                         (*reason == WIFI_PROV_STA_AUTH_ERROR) ? "Authentication Error" : "Access Point Not Found");
                break;
            }
            case WIFI_PROV_CRED_SUCCESS:
                ESP_LOGI(TAG, "Provisioning successfully connected to Wi-Fi AP!");
                break;
            case WIFI_PROV_END:
                ESP_LOGI(TAG, "Provisioning service ended");
                break;
            default:
                break;
        }
    }
}

static void mqtt_event_handler(void *handler_args, esp_event_base_t base, int32_t event_id, void *event_data) {
    esp_mqtt_event_handle_t event = event_data;
    switch ((esp_mqtt_event_id_t)event_id) {
        case MQTT_EVENT_CONNECTED:
            ESP_LOGI(TAG, "MQTT Connected");
            esp_mqtt_client_subscribe(s_mqtt_client, CLOUD_MQTT_TOPIC_COMMAND, 1);
            break;
        case MQTT_EVENT_DISCONNECTED:
            ESP_LOGI(TAG, "MQTT Disconnected");
            break;
        case MQTT_EVENT_DATA:
            ESP_LOGI(TAG, "MQTT Data Received: topic=%.*s", event->topic_len, event->topic);
            if (event->topic_len == strlen(CLOUD_MQTT_TOPIC_COMMAND) &&
                strncmp(event->topic, CLOUD_MQTT_TOPIC_COMMAND, event->topic_len) == 0) {
                hub_handle_mqtt_command(event->data, event->data_len);
            }
            break;
        default:
            break;
    }
}

static void wifi_init_sta(void) {
    s_wifi_event_group = xEventGroupCreate();
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    esp_netif_t *sta_netif = esp_netif_create_default_wifi_sta();
    assert(sta_netif);

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK( esp_wifi_init(&cfg) );

    ESP_ERROR_CHECK( esp_event_handler_register(WIFI_EVENT, ESP_EVENT_ANY_ID, &event_handler, NULL) );
    ESP_ERROR_CHECK( esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, &event_handler, NULL) );
    ESP_ERROR_CHECK( esp_event_handler_register(WIFI_PROV_EVENT, ESP_EVENT_ANY_ID, &prov_event_handler, NULL) );

    ESP_ERROR_CHECK( esp_wifi_set_mode(WIFI_MODE_STA) );

#if defined(WIFI_SSID) && defined(WIFI_PASS)
    if (strlen(WIFI_SSID) > 0) {
        ESP_LOGI(TAG, "Configuring WiFi using static credentials from secrets.h: %s", WIFI_SSID);
        wifi_config_t wifi_config = {
            .sta = {
                .threshold.rssi = -127,
                .pmf_cfg = {
                    .capable = true,
                    .required = false
                },
            },
        };
        strncpy((char *)wifi_config.sta.ssid, WIFI_SSID, sizeof(wifi_config.sta.ssid) - 1);
        strncpy((char *)wifi_config.sta.password, WIFI_PASS, sizeof(wifi_config.sta.password) - 1);
        ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));
    } else {
        ESP_LOGI(TAG, "WiFi static credentials empty. Using saved NVS credentials or BLE Provisioning.");
    }
#else
    ESP_LOGI(TAG, "WiFi static credentials not defined. Using saved NVS credentials or BLE Provisioning.");
#endif

    ESP_ERROR_CHECK( esp_wifi_start() );
}

static bool has_static_wifi(void) {
#if defined(WIFI_SSID) && defined(WIFI_PASS)
    return strlen(WIFI_SSID) > 0;
#else
    return false;
#endif
}

// Callback endpoint handler for receiving secure cloud certificates and MQTT settings dynamically
static esp_err_t custom_prov_handler(uint32_t session_id, const uint8_t *in_data, ssize_t in_len,
                             uint8_t **out_data, ssize_t *out_len, void *priv_data) {
    ESP_LOGI(TAG, "Received data on custom endpoint 'cloud-config': %.*s", (int)in_len, (char *)in_data);
    
    char *in_str = malloc(in_len + 1);
    if (!in_str) return ESP_ERR_NO_MEM;
    memcpy(in_str, in_data, in_len);
    in_str[in_len] = '\0';
    
    cJSON *json = cJSON_Parse(in_str);
    free(in_str);
    
    if (json == NULL) {
        ESP_LOGE(TAG, "Failed to parse incoming JSON configuration");
        const char *resp = "{\"status\":\"error\",\"message\":\"Invalid JSON\"}";
        *out_data = (uint8_t *)strdup(resp);
        *out_len = strlen(resp);
        return ESP_OK;
    }
    
    cJSON *ca_cert = cJSON_GetObjectItem(json, "ca_cert");
    cJSON *broker_uri = cJSON_GetObjectItem(json, "broker_uri");
    cJSON *username = cJSON_GetObjectItem(json, "username");
    cJSON *password = cJSON_GetObjectItem(json, "password");
    
    bool success = true;
    if (ca_cert && cJSON_IsString(ca_cert)) {
        if (secure_store_write_string(NVS_KEY_CA_CERT, ca_cert->valuestring) != ESP_OK) success = false;
    }
    if (broker_uri && cJSON_IsString(broker_uri)) {
        if (secure_store_write_string(NVS_KEY_BROKER_URI, broker_uri->valuestring) != ESP_OK) success = false;
    }
    if (username && cJSON_IsString(username)) {
        if (secure_store_write_string(NVS_KEY_USERNAME, username->valuestring) != ESP_OK) success = false;
    }
    if (password && cJSON_IsString(password)) {
        if (secure_store_write_string(NVS_KEY_PASSWORD, password->valuestring) != ESP_OK) success = false;
    }
    
    cJSON_Delete(json);
    
    const char *resp;
    if (success) {
        ESP_LOGI(TAG, "Dynamic cloud configurations successfully stored in secure NVS!");
        resp = "{\"status\":\"success\",\"message\":\"Cloud configurations saved successfully\"}";
    } else {
        ESP_LOGE(TAG, "Failed to write cloud configuration elements to secure NVS");
        resp = "{\"status\":\"error\",\"message\":\"NVS secure write failed\"}";
    }
    
    *out_data = (uint8_t *)strdup(resp);
    *out_len = strlen(resp);
    return ESP_OK;
}

// Loads credentials dynamically from secure NVS storage
static void load_cloud_configs_from_nvs(void) {
    size_t size = sizeof(s_cloud_ca_cert);
    if (secure_store_read_string(NVS_KEY_CA_CERT, s_cloud_ca_cert, size) == ESP_OK) {
        ESP_LOGI(TAG, "Successfully loaded custom TLS CA certificate from NVS");
    }
    
    size = sizeof(s_cloud_broker_uri);
    if (secure_store_read_string(NVS_KEY_BROKER_URI, s_cloud_broker_uri, size) == ESP_OK) {
        ESP_LOGI(TAG, "Successfully loaded custom Broker URI: %s", s_cloud_broker_uri);
    }
    
    size = sizeof(s_cloud_username);
    if (secure_store_read_string(NVS_KEY_USERNAME, s_cloud_username, size) == ESP_OK) {
        ESP_LOGI(TAG, "Successfully loaded custom MQTT username: %s", s_cloud_username);
    }
    
    size = sizeof(s_cloud_password);
    if (secure_store_read_string(NVS_KEY_PASSWORD, s_cloud_password, size) == ESP_OK) {
        ESP_LOGI(TAG, "Successfully loaded custom MQTT password");
    }
}

static void provisioning_task(void * parm) {
    if (has_static_wifi()) {
        ESP_LOGI(TAG, "Waiting for WiFi connection (static credentials)...");
        xEventGroupWaitBits(s_wifi_event_group, CONNECTED_BIT, false, true, portMAX_DELAY);
        ESP_LOGI(TAG, "Connected to WiFi successfully using static credentials.");
    } else {
        // Initialize provisioning manager with BLE scheme
        wifi_prov_mgr_config_t config = {
            .scheme = wifi_prov_scheme_ble,
            .scheme_event_handler = WIFI_PROV_SCHEME_BLE_EVENT_HANDLER_FREE_BTDM
        };
        ESP_ERROR_CHECK(wifi_prov_mgr_init(config));
        
        bool provisioned = false;
        ESP_ERROR_CHECK(wifi_prov_mgr_is_provisioned(&provisioned));
        
        if (provisioned) {
            ESP_LOGI(TAG, "WiFi credentials already present in NVS. Starting normal connection...");
            wifi_prov_mgr_deinit();
            
            esp_wifi_connect();
            
            ESP_LOGI(TAG, "Waiting for WiFi connection (saved credentials)...");
            xEventGroupWaitBits(s_wifi_event_group, CONNECTED_BIT, false, true, portMAX_DELAY);
            ESP_LOGI(TAG, "Connected to WiFi successfully using saved credentials.");
        } else {
            ESP_LOGI(TAG, "No WiFi credentials found in NVS. Starting BLE Provisioning...");
            s_provisioning_mode = true;
            
            // Generate distinct BLE advertising name from MAC address
            uint8_t eth_mac[6];
            esp_wifi_get_mac(WIFI_IF_STA, eth_mac);
            char service_name[16];
            snprintf(service_name, sizeof(service_name), "PROV_%02X%02X%02X", eth_mac[3], eth_mac[4], eth_mac[5]);
            
            // Proof of Possession (PoP) PIN code for secure association
            const char *pop = "12345678";
            
            // Display provisioning pairing details and QR Code Generation link in console
            ESP_LOGI(TAG, "==========================================================================");
            ESP_LOGI(TAG, "BLE PROVISIONING SERVICE RUNNING");
            ESP_LOGI(TAG, "BLE SSID / Name           : %s", service_name);
            ESP_LOGI(TAG, "Proof of Possession (PoP) : %s", pop);
            ESP_LOGI(TAG, "JSON QR Code Payload      :");
            ESP_LOGI(TAG, "{\"ver\":\"v1\",\"name\":\"%s\",\"pop\":\"%s\",\"transport\":\"ble\"}", service_name, pop);
            ESP_LOGI(TAG, "Generate QR Code URL      :");
            ESP_LOGI(TAG, "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=%%7B%%22ver%%22%%3A%%22v1%%22%%2C%%22name%%22%%3A%%22%s%%22%%2C%%22pop%%22%%3A%%22%s%%22%%2C%%22transport%%22%%3A%%22ble%%22%%7D", service_name, pop);
            ESP_LOGI(TAG, "==========================================================================");
            
            // Register custom endpoint to accept CA certs and server URI
            wifi_prov_mgr_endpoint_create("cloud-config");
            wifi_prov_mgr_endpoint_register("cloud-config", custom_prov_handler, NULL);
            
            // Start BLE Provisioning scheme
            ESP_ERROR_CHECK(wifi_prov_mgr_start_provisioning(WIFI_PROV_SECURITY_1, pop, service_name, NULL));
            
            // Wait for successful provisioning
            wifi_prov_mgr_wait();
            
            // Release BLE stack and de-initialize manager to free internal memory
            wifi_prov_mgr_deinit();
            s_provisioning_mode = false;
            
            ESP_LOGI(TAG, "Waiting for WiFi connection (newly provisioned credentials)...");
            xEventGroupWaitBits(s_wifi_event_group, CONNECTED_BIT, false, true, portMAX_DELAY);
            ESP_LOGI(TAG, "Connected to WiFi successfully using provisioned credentials.");
        }
    }

    // Initialize SNTP for clock synchronization
    ESP_LOGI(TAG, "Initializing SNTP clock synchronization...");
    esp_sntp_setoperatingmode(ESP_SNTP_OPMODE_POLL);
    esp_sntp_setservername(0, "pool.ntp.org");
    esp_sntp_init();

    // Read MQTT cloud broker configurations and TLS certificates from NVS if set
    load_cloud_configs_from_nvs();

    // Connect to MQTT Broker securely
    esp_mqtt_client_config_t mqtt_cfg = {0};
    
    if (strlen(s_cloud_broker_uri) > 0) {
        mqtt_cfg.broker.address.uri = s_cloud_broker_uri;
    } else {
        mqtt_cfg.broker.address.uri = CLOUD_MQTT_URI;
    }
    
    if (strlen(s_cloud_ca_cert) > 0) {
        mqtt_cfg.broker.verification.certificate = s_cloud_ca_cert;
    } else {
        mqtt_cfg.broker.verification.certificate = (const char *)_binary_certs_ca_crt_start;
    }
    
    if (strlen(s_cloud_username) > 0) {
        mqtt_cfg.credentials.username = s_cloud_username;
    } else {
        mqtt_cfg.credentials.username = CLOUD_MQTT_USERNAME;
    }
    
    if (strlen(s_cloud_password) > 0) {
        mqtt_cfg.credentials.authentication.password = s_cloud_password;
    } else {
        mqtt_cfg.credentials.authentication.password = CLOUD_MQTT_PASSWORD;
    }

    ESP_LOGI(TAG, "Connecting to MQTT broker: %s...", mqtt_cfg.broker.address.uri);
    s_mqtt_client = esp_mqtt_client_init(&mqtt_cfg);
    esp_mqtt_client_register_event(s_mqtt_client, ESP_EVENT_ANY_ID, mqtt_event_handler, NULL);
    esp_mqtt_client_start(s_mqtt_client);

    vTaskDelete(NULL);
}

void cloud_task_init(void) {
    wifi_init_sta();
    xTaskCreate(provisioning_task, "provisioning_task", 8192, NULL, 3, NULL);
}

esp_err_t cloud_publish_alarm(const uint8_t *mac, uint8_t alarm_code) {
    if (!s_mqtt_client) return ESP_FAIL;
    
    char payload[128];
    snprintf(payload, sizeof(payload), "{\"type\":\"ALARM\", \"mac\":\"%02x:%02x:%02x:%02x:%02x:%02x\", \"alarm\":%d}",
             mac[0], mac[1], mac[2], mac[3], mac[4], mac[5], alarm_code);
             
    int msg_id = esp_mqtt_client_publish(s_mqtt_client, CLOUD_MQTT_TOPIC_STATUS, payload, 0, 1, 0);
    if (msg_id >= 0) {
        ESP_LOGI(TAG, "Published alarm info to cloud");
        return ESP_OK;
    }
    return ESP_FAIL;
}

esp_err_t cloud_publish_response(const char *payload) {
    if (!s_mqtt_client) return ESP_FAIL;
    
    int msg_id = esp_mqtt_client_publish(s_mqtt_client, CLOUD_MQTT_TOPIC_RESPONSE, payload, 0, 1, 0);
    if (msg_id >= 0) {
        ESP_LOGI(TAG, "Published response to cloud");
        return ESP_OK;
    }
    return ESP_FAIL;
}
